### ISSUE TITLE
Some DramaCool links not resolving in Leia

### ISSUE THREAD

**Issue by xalagaco** [Gujal00/ResolveURL#134]
DramaCool by groggyegg has a bunch of links that work in Matrix 19.4 but not in Leia 18.9.
There used to be just one, Xstreamcdn, that was working, now Streamtape also works in Leia (I think since 5.1.67?).
However usually reliable links in Matrix, StreamDB, Mixdrop, and Doodstream, stopped working in Leia.
Currently on 5.1.69 for both, on Firestick 4K.

**Comment by Gujal00** [comment]
test those embeds using smr link tester in Leia. All embeds that you mention above such as mixdrop, dood, streamsb,  xtreamcdn and are tested in both Leia and Matrix and have been working for a long time.
If you find any embed that work in Matrix but not in Leia, link it here so that it can be checked out
OpenSSL bundled in Leia Windows/Android is quite old and end of life, so it will progressively get harder and harder to keep it working.

**Comment by xalagaco** [comment]
How do I do that exactly?
I can make it fail at will on Leia, but then there is no URL tied to that server in the log.

**Comment by Gujal00** [comment]
1. Install Kodi Logfile Uploader addon from Offcial Kodi Repository under Program add-ons.
2. Enable Debug logging, (Settings - System - Logging - Enable Debug Logging)
3. Restart Kodi (Important)
4. Go into the addon and open the link (wait for the error message)
5. Come out of addon
6. Disable Debug logging, (Settings - System - Logging - Enable Debug Logging off)
7. launch Kodi Logfile uploader and upload your log. This will give you a url
8. provide the url from step 7 here

**Comment by xalagaco** [comment]
Thank you for the instructions, that's so helpful.
Here's the [log](https://paste.kodi.tv/ojacuhihid) when I tried the Doodstream link of Our Blues E1.
When I tried the [URL](https://dood.ws/d/fl62zfpzsyss) in the SMR Link Tester, the video plays just fine in Leia.
So, at this point ResolveURL is off the hook, closing ticket as invalid.
Again, thank you for your support. Back to groggyegg. . .
