### ISSUE TITLE
DoodStream issue

### ISSUE THREAD

**Issue by dracosc22679** [Gujal00/ResolveURL#253]
I get this error when resolving doodstream. (Failed: Peer certificate cannot be authenticated with given CA certificates(60)
If i manually edit doodstream.py from: return self.dood_decode(html) + token + str(int(time.time() * 1000)) + helpers.append_headers(headers)
to:
return self.dood_decode(html) + token + str(int(time.time() * 1000)) + '|User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36&verifypeer=false&Connection=keep-alive&Referer=%s' % (web_url)
it works!

**Comment by shellc0de27** [comment]
@dracosc22679 Can you provide the doodstream url that's not resolving? Thanks

**Comment by dracosc22679** [comment]
https://dood.pm/e/9mwenbo4lq9aguzpjgcb3a9cdorywcy0?
found in a page for Deadpool 2 movie

**Comment by Gujal00** [comment]
Plays fine with current resolver without any changes
`
INFO <general>: SMR Link Tester: Link Resolved: |https://dood.pm/e/9mwenbo4lq9aguzpjgcb3a9cdorywcy0|https://d312ow.dood.video/u5kj6zukedhlsdgge4jgciqakbwnuqoyxlvhgxv6hbdnxh7xtpuh4ytpbotq/73kk6k16kv~mncjLOXWKy?token=0jf04a9mm4dxzl1l87nj5ai9&expiry=1667412019499|User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F84.0.4136.7+Safari%2F537.36&Referer=https%3A%2F%2Fdood.pm%2Fd%2F9mwenbo4lq9aguzpjgcb3a9cdorywcy0|
`

**Comment by dracosc22679** [comment]
Using Kodi 18.9 . For me it needs &verifypeer=false&Connection=keep-alive in final url to work.... Strange!!!

**Comment by Gujal00** [comment]
ON what platform?
Kodi ships with its own cert store that it will trust and that could be different from platform to platform.

Kodi 18.9 on Windows works plays that link fine

**Comment by pitsi** [comment]
I can also report that doodstream fails to play on kodi 18.9 of libreelec x64 9.2.6. Log from smr link tester for the forementioned url
```
2022-11-22 21:03:48.409 T:139989341886208  NOTICE: SMR Link Tester: Version: |1.1.9| Queries: |{'link': 'https://dood.pm/e/9mwenbo4lq9aguzpjgcb3a9cdorywcy0', 'mode': 'play_link'}| (ENCODED)
2022-11-22 21:03:48.409 T:139989341886208  NOTICE: SMR Link Tester: Running on: Python 2.7.16 (default, Oct 25 2020, 09:34:29)
                                            [GCC 8.3.0]|OpenSSL 1.1.1d  10 Sep 2019
2022-11-22 21:03:48.409 T:139989341886208  NOTICE: SMR Link Tester: Args: |['plugin://plugin.video.smr_link_tester/', '3', '?link=https%3A%2F%2Fdood.pm%2Fe%2F9mwenbo4lq9aguzpjgcb3a9cdorywcy0&mode=play_link', 'resume:false']|
2022-11-22 21:03:48.409 T:139989341886208  NOTICE: SMR Link Tester: Playing Link: |https://dood.pm/e/9mwenbo4lq9aguzpjgcb3a9cdorywcy0|
2022-11-22 21:03:48.465 T:139989341886208  NOTICE: SMR Link Tester: Link Supported: |https://dood.pm/e/9mwenbo4lq9aguzpjgcb3a9cdorywcy0| Resolvers: DoodStream
2022-11-22 21:03:48.780 T:139989341886208   ERROR: ResolveURL: HTTPError Error - From: DoodStream Link: https://dood.pm/e/9mwenbo4lq9aguzpjgcb3a9cdorywcy0: HTTP Error 403: Forbidden
2022-11-22 21:03:48.840 T:139990842468480   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.smr_link_tester/?link=https%3A%2F%2Fdood.pm%2Fe%2F9mwenbo4lq9aguzpjgcb3a9cdorywcy0&mode=play_link]
```
The same url plays with no issues on kodi 19.4 of libreelec x64 10.0.3 (on the same system, under the same network etc).

**Comment by Gujal00** [comment]
> I can also report that doodstream fails to play on kodi 18.9 of libreelec x64 9.2.6. Log from smr link tester for the forementioned url
> 
> The same url plays with no issues on kodi 19.4 of libreelec x64 10.0.3 (on the same system, under the same network etc).
Completely different issue. Your issue is a straight up 403 error which happens due to Python 2.7.16 as used by LE 9.2.6 does not have the newer ssl encryption mechanisms expected by modern websites as it is using OpenSSL 1.1.1d
LE 10.0.3 is using OpenSSL 1.1.1q which supports more mechanisms and so works.

**Comment by pitsi** [comment]
You are right about that.
However, that 403 error is what I got yesterday with the forementioned url I think was different a couple of days ago that I first tried a different doodstream url. 
That url had a 12-character string on it, instead of the one above which is 32-characters long. I can't post it because it's... porn. Today, it does return 403 error though.

**Comment by pitsi** [comment]
Honest question. Leaving my le 9.2.6 x64 installation aside, because it can not be upgraded to get a newer version of openssl, I resorted to a friend's le 9.2.8.x installation which is on an old tvbox. Its last update updated openssl to 1.1.1t as you can see in its changelog here
https://github.com/dtechsrv/LibreELEC-AML/releases/tag/9.2.8.8

However, the forementioned doodstream url still does not play. Any idea why? Unfortunately, she can not provide me with a log because she does not know anything but the basics of kodi.

**Comment by Gujal00** [comment]
@pitsi read this thread from [this comment](https://github.com/Gujal00/ResolveURL/issues/324#issuecomment-1408021557) onwards
It could specifically be your ISP issue as mentioned in that thread
