### ISSUE TITLE
New Resolver for abyss.to

### ISSUE THREAD

**Issue by DWH-WFC** [Gujal00/ResolveURL#339]
Hello from Germany.
Is it possible to write a resolver for https://abyss.to/ ?

Sorry I don't have links to videos

**Comment by Gujal00** [comment]
Unfortunately cant write a plugin without a embed to look at
Why do you need a resolver if you dont have any videos to resolve :)

**Comment by DWH-WFC** [comment]
Sorry I was mobile with my phone yesterday so I didn't have a link to a video.

It's about the website https://topstreamfilme.io for which we need a resolver.

Here is a link to a video
https://topstreamfilm.io/?trembed=0&trid=14114&trtype=1

I created an account there to get the necessary information.

CURL (Document)
curl -F "file=@demo.mp4" up.hydrax.net/24e9c40c26aabeb1510b73acc7f0f8d7

Python (document)
import requests

url=url='http://up.hydrax.net/24e9c40c26aabeb1510b73acc7f0f8d7'

file_name = 'demo.mp4'
file_type = 'video/mp4'
file_path = './demo.mp4'
files = { 'file': (file_name, open(file_path, 'rb'), file_type) }

r = requests.post(url, files=files)
print(r.text)

Here is a link to a video I made myself
https://short.ink/JJvb-5qqZ
the NameServer (short.ink) can be set variably.

but it's all about the website. Is it possible to create a resolver there?

**Comment by Gujal00** [comment]
Ah, It is Hydrax which is a fake hoster hiding files on googledrive and have a javascript obfuscated tls1.3 enforcing website to cover it up.
Can't use debugger as the javascript kills your browser by consuming all the memory if you do and cant use proxies to sniff as it enforces tls1.3.
Going from `https://abysscdn.com/?v=MzOVLvbrmX` to `http://up.hydrax.net/24e9c40c26aabeb1510b73acc7f0f8d7` is the thing that is currently not possible to figure out due to obfuscation
