### ISSUE TITLE
streamhide resolver not working

### ISSUE THREAD

**Issue by DWH-WFC** [Gujal00/ResolveURL#368]
Hello from germany.

The resolver streamhide no longer works for me. Maybe you could fix it.

URL: `https://streamhide.to/e/23faz5ttlkv7`

Many thanks for your work

**Comment by Gujal00** [comment]
Fixed in https://github.com/Gujal00/ResolveURL/commit/5bf10038496f6bcb53ea8e721c63e92e9b89414f
`SMR Link Tester: Link Resolved: |https://streamhide.to/e/23faz5ttlkv7|https://cdn009.sh-content.com/hls2/01/00056/23faz5ttlkv7_x/master.m3u8?t=rE78jpumQT341xy4V2zkKL7W6Yy06AEYwbj7zuBfRMI&s=1677180467&e=129600&f=281517&srv=sto004&i=0.0&sp=500&p1=sto004&p2=sto004|User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F80.0.3987.132+Safari%2F537.36+OPR%2F67.0.3575.97&Referer=https%3A%2F%2Fstreamhide.to%2F&Origin=https%3A%2F%2Fstreamhide.to|`
