### ISSUE TITLE
StreamSB plugin is broken

### ISSUE THREAD

**Issue by w64** [Gujal00/ResolveURL#514]
Please fix it:  https://paste.kodi.tv/begulixela

**Comment by shellc0de27** [comment]
@w64 the plugin is not broken. Have a look at the log you posted. Getting a 502 error which is server side and NOT an issue ResolveURL. Streamsb domains are notorious for this, especially on weekends as they get hit pretty damn hard. Took a few tries due to time out issues, but as you can see it works fine:

`SMR Link Tester: Playing Link: |https://sbnet.one/e/09z7b22mcf4s
SMR Link Tester: Link Supported: |https://sbnet.one/e/09z7b22mcf4s| Resolvers: StreamSB
SMR Link Tester: Link Resolved: |https://sbnet.one/e/09z7b22mcf4s|https://sto204.akamai-video-content.com/tysxft4vs27oj6cdacydfhyihhm6g4cvafn35fcqbdor4bzns6nslwwetpaq/feria-the-darkest-light-season-1-episode-1-el-lago-rojo1675654201.0.mp4|User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F70.0.3538.102+Safari%2F537.36+Edge%2F18.18363&Referer=https%3A%2F%2Fsbnet.one%2F|`

**Comment by w64** [comment]
@shellc0de27 , you are right. Thank you!
