### ISSUE TITLE
mixdrop.ms and possibility to add domains themselves

### ISSUE THREAD

**Issue by teletcl** [Gujal00/ResolveURL#785]
New domain "mixdrop.ms".
Could You added it?

Could it be possible to make it possible for a user to add domains themselves, In settings?
This would involve adding to variable "domains" and "pattern" in the class of plugin.

**Comment by MrDini123** [comment]
While I am personally in love with the idea to add that feature, I don't think that the average John Doe will want to deal with those regexes for themselves. Plus if you have a field in settings with a custom regex, how would you handle updates to that from the upstream source (ie. Gujal00 adds a new domain), but also preserve your local changes? It would just be a mess to offer support then, because you can't tell if the user's regex is wrong or something in the code causes a resolver error...

I think it would increase the complexity of the addon too much, and its probably not the most ideal solution. I would be more for a feature that checks DNS servers of a given domain on hosts where the domains frequently change.

**Comment by teletcl** [comment]
I was thinking more of a temporary entry until the update comes out.
Based on the "mixdrop" plugin, I created proposal code.
The "domains" variable is easier to modify, but the "pattern" variable can also be modified. I was wondering whether to divide it into "user_pattern".
If something repeats in the pattern, it is not a problem.
```python
# taken from "mixdrop.py"
domains = ['mixdrop.co', 'mixdrop.to']
pattern = r'(?://|\.)((?:mixdro*p\d*(?:jmk)?|md(?:3b0j6hj|bekjwqa|fx9dc8n|y48tn97|zsmutpcvykb))\.' \
          r'(?:c[ho]m?|to|sx|bz|gl|club|vc|ag|pw|net|is|si|nu|ms))/(?:f|e)/(\w+)'

user_domains = 'new1.net, new2.bl'  # get it from setting as string
if user_domains:  # if user set something
    user_domains = user_domains.strip(',. ')  # clean something
    user_domains = user_domains.split(', ')
    user_domains = list(filter(None, user_domains))  # eliminate empty
    user_domains = list(dict.fromkeys(user_domains))  # eliminate duplicates
    user_domains = [d for d in user_domains if d not in domains]  # eliminate exists
    if user_domains:  # if is something to add
        domains += user_domains

        #user_pattern = ''  # don't know if is needed
        if user_domains:
            ud_name = ud_dot = ''
            for user_domain in user_domains:
                ud = user_domain.split('.')
                ud_name += f"|{ud[0]}"
                ud_dot += f"|{ud[1]}"
            #user_pattern = rf'(?://|\.)((?:{ud_name.lstrip("|")})\.(?:{ud_dot.lstrip("|")}))/(?:f|e)/(\w+)'
            #print(user_pattern)  # result

            pattern = pattern.replace(r'))\.', rf'{ud_name}))\.', 1)
            pattern = pattern.replace('))/', f'{ud_dot}))/', 1)

        # result
        print(domains)
        print(pattern)
```

**Comment by teletcl** [comment]
@MrDini123 
I've moved to another thread https://github.com/Gujal00/ResolveURL/issues/795
Can You take a look?
